ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Models/ErrorViewModel.cs
namespace FootBallLeague.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Models/ScoreBoard.cs
using System.ComponentModel.DataAnnotations;

namespace FootBallLeague.Models
{
    public class ScoreBoard
    {
        [Key]
        public int MatchId { get; set; }
        [Required(ErrorMessage ="Need To Enter the Details")]
        public string TeamName1 { get; set; }
        [Required(ErrorMessage ="Need To Enter The Details")]
        public string TeamName2 { get; set;}
        [Required(ErrorMessage ="Need To Enter The Details")]
        public string Status { get; set; }
        public string WinningTeams { get; set; }
        [Required(ErrorMessage ="Need To Enter The Details")]
        public int Points { get; set;}

    }
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Controllers/HomeController.cs
using FootBallLeague.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FootBallLeague.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Controllers/ScoreBoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FootBallLeague;
using FootBallLeague.Models;

namespace FootBallLeague.Controllers
{
    public class ScoreBoardsController : Controller
    {
        private readonly FootBallLeagueContextDB _context;

        public ScoreBoardsController(FootBallLeagueContextDB context)
        {
            _context = context;
        }

        // GET: ScoreBoards
        public async Task<IActionResult> Index()
        {
              return View(await _context.ScoreBoards.ToListAsync());
        }
        // Show list of winners
        public async Task<IActionResult> Winners()
        {
            var TotalList = await _context.ScoreBoards.ToListAsync();
            var WinnersList = TotalList.Where(team => team.Points == 4);
            return View(WinnersList);
        }


        // GET: ScoreBoards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ScoreBoards == null)
            {
                return NotFound();
            }

            var scoreBoard = await _context.ScoreBoards
                .FirstOrDefaultAsync(m => m.MatchId == id);
            if (scoreBoard == null)
            {
                return NotFound();
            }

            return View(scoreBoard);
        }

        // GET: ScoreBoards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ScoreBoards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MatchId,TeamName1,TeamName2,Status,WinningTeams,Points")] ScoreBoard scoreBoard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scoreBoard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scoreBoard);
        }

        // GET: ScoreBoards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ScoreBoards == null)
            {
                return NotFound();
            }

            var scoreBoard = await _context.ScoreBoards.FindAsync(id);
            if (scoreBoard == null)
            {
                return NotFound();
            }
            return View(scoreBoard);
        }

        // POST: ScoreBoards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MatchId,TeamName1,TeamName2,Status,WinningTeams,Points")] ScoreBoard scoreBoard)
        {
            if (id != scoreBoard.MatchId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scoreBoard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScoreBoardExists(scoreBoard.MatchId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scoreBoard);
        }

        // GET: ScoreBoards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ScoreBoards == null)
            {
                return NotFound();
            }

            var scoreBoard = await _context.ScoreBoards
                .FirstOrDefaultAsync(m => m.MatchId == id);
            if (scoreBoard == null)
            {
                return NotFound();
            }

            return View(scoreBoard);
        }

        // POST: ScoreBoards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ScoreBoards == null)
            {
                return Problem("Entity set 'FootBallLeagueContextDB.ScoreBoards'  is null.");
            }
            var scoreBoard = await _context.ScoreBoards.FindAsync(id);
            if (scoreBoard != null)
            {
                _context.ScoreBoards.Remove(scoreBoard);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScoreBoardExists(int id)
        {
          return _context.ScoreBoards.Any(e => e.MatchId == id);
        }
    }
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Create.cshtml
@model FootBallLeague.Models.ScoreBoard

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ScoreBoard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TeamName1" class="control-label"></label>
                <input asp-for="TeamName1" class="form-control" />
                <span asp-validation-for="TeamName1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeamName2" class="control-label"></label>
                <input asp-for="TeamName2" class="form-control" />
                <span asp-validation-for="TeamName2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WinningTeams" class="control-label"></label>
                <input asp-for="WinningTeams" class="form-control" />
                <span asp-validation-for="WinningTeams" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Points" class="control-label"></label>
                <input asp-for="Points" class="form-control" />
                <span asp-validation-for="Points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Delete.cshtml
@model FootBallLeague.Models.ScoreBoard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ScoreBoard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WinningTeams)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WinningTeams)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Points)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MatchId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Details.cshtml
@model FootBallLeague.Models.ScoreBoard

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ScoreBoard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WinningTeams)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WinningTeams)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Points)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MatchId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Edit.cshtml
@model FootBallLeague.Models.ScoreBoard

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ScoreBoard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MatchId" />
            <div class="form-group">
                <label asp-for="TeamName1" class="control-label"></label>
                <input asp-for="TeamName1" class="form-control" />
                <span asp-validation-for="TeamName1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeamName2" class="control-label"></label>
                <input asp-for="TeamName2" class="form-control" />
                <span asp-validation-for="TeamName2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WinningTeams" class="control-label"></label>
                <input asp-for="WinningTeams" class="form-control" />
                <span asp-validation-for="WinningTeams" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Points" class="control-label"></label>
                <input asp-for="Points" class="form-control" />
                <span asp-validation-for="Points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Index.cshtml
@model IEnumerable<FootBallLeague.Models.ScoreBoard>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TeamName1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeamName2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WinningTeams)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Points)
            </th>
            <th><button type="button" class="btn btn-primary" 
                onclick="location.href='@Url.Action("Winners", "ScoreBoards")'">WinnersList</button></th>
        </tr>

    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WinningTeams)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Points)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MatchId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MatchId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MatchId">Delete</a>
            </td>
        </tr>
}

    </tbody>
</table>

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/ScoreBoards/Winners.cshtml
@model IEnumerable<FootBallLeague.Models.ScoreBoard>

@{
    ViewData["Title"] = "Winners";
}

<h1>Winners</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TeamName1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeamName2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WinningTeams)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Points)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WinningTeams)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Points)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MatchId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MatchId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MatchId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ADO.NET and LINQ and Entity Framework Assignment1/FootBallLeague/FootBallLeague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FootBallLeague</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FootBallLeague.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FootBallLeague</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FootBallLeague - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>