ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Models/ErrorViewModel.cs
namespace PKRTravels.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Models/TravelsDB.cs
using System.ComponentModel.DataAnnotations;

namespace PKRTravels.Models
{
    //Creating the model of PKR Travels
    public class TravelsDB
    {
        [Key]
        public int BusId { get; set; }
        [Required]
        public string BoardingPoint { get; set; }
        [Required]
        public DateTime TravelDate { get; set; }
        [Required]
        public float Amount { get; set; }
        [Required]
        public int Rating { get; set; }

    }
}

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace PKRTravels.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Controllers/TravelsController.cs
using Microsoft.AspNetCore.Mvc;
using PKRTravels.Models;

namespace PKRTravels.Controllers
{
    public class TravelsController : Controller
    {
        private readonly ContextDB context;
        public TravelsController(ContextDB _context)
        {
            this.context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult create(TravelsDB travels)
        {
            if (ModelState.IsValid)
            {
                context.TravelsDBs.Add(travels);
                context.SaveChanges();
                return Ok("Successfully created");
            }
            return View(travels);
        }
        public IActionResult ListOfBuses(TravelsDB travels)
        {
           var arr= context.TravelsDBs.ToList();
         return View(arr);
        }
    }
}

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a >building Web apps with ASP.NET Core</a>.</p>
    <b>

    </b>
    <button type="button" class="btn btn-primary"
            onclick="location.href='@Url.Action("List Of Buses", "Travels")'">
        Buses List
    </button></th>
    </tr>

</div>

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PKRTravels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PKRTravels.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PKRTravels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PKRTravels - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Views/Travels/ListOfBuses.cshtml
@model IEnumerable<PKRTravels.Models.TravelsDB>

@{
    ViewData["Title"] = "ListOfBuses";
}

<h1>ListOfBuses</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BoardingPoint)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TravelDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BoardingPoint)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TravelDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BusId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BusId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BusId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Views/Travels/create.cshtml
@model PKRTravels.Models.TravelsDB

@{
    ViewData["Title"] = "create";
}

<h1>create</h1>

<h4>TravelsDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BoardingPoint" class="control-label"></label>
                <input asp-for="BoardingPoint" class="form-control" />
                <span asp-validation-for="BoardingPoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TravelDate" class="control-label"></label>
                <input asp-for="TravelDate" class="form-control" />
                <span asp-validation-for="TravelDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Create">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ADO.NET and LINQ and Entity Framework Assignment2/PKRTravels/PKRTravels/Views/TravelsDBs/Edit.cshtml
@model PKRTravels.Models.TravelsDB

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TravelsDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BusId" />
            <div class="form-group">
                <label asp-for="BoardingPoint" class="control-label"></label>
                <input asp-for="BoardingPoint" class="form-control" />
                <span asp-validation-for="BoardingPoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TravelDate" class="control-label"></label>
                <input asp-for="TravelDate" class="form-control" />
                <span asp-validation-for="TravelDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}